/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-02 07:29:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<!-- bootstrap 라이브러리 등록 :CDN 방식 -->\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  $( function() {\r\n");
      out.write("\t  // 생년월일 날짜 캘린더 \r\n");
      out.write("    $( \"#birth\" ).datepicker();\r\n");
      out.write("    $( \"#birth\" ).datepicker( \"option\", \"dateFormat\", \"yy-mm-dd\");\r\n");
      out.write("\r\n");
      out.write("  // 이벤트 처리 \r\n");
      out.write("  $(\"#id\").on(\"keyup\", function() {\r\n");
      out.write("// \t\talert(\"아이디입력\");\r\n");
      out.write("//\t\t입력한 아이디의 값을 가져와서 앞뒤 공백 제거 한다.\r\n");
      out.write("\t\tvar id = $(\"#id\").val().trim();\r\n");
      out.write("\t\t//공백을 제거한 아이디를 다시 아이디 입력란에 셋팅해 준다. \r\n");
      out.write("\t\t$(\"#id\").val(id);\r\n");
      out.write("\t\tif(id.length == 0){\r\n");
      out.write("\t\t\t$(\"#idCheck\").html(\"아이디를 입력하셔야만 합니다.\");\r\n");
      out.write("\t\t}else if(id.length < 4 || id.length > 20){\r\n");
      out.write("\t\t\t$(\"#idCheck\").html(\"아이디는 4자이상 20자 이내로 작성하셔야 합니다.\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t// Ajax를 이용해서 서버에 갔다가 오면서 결과를 idCheck에 넣는다.\r\n");
      out.write("\t\t\t$(\"#idCheck\").load(\"/ajax/idCheck.do?id=\"+id);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("  $(\"#joinForm\").on(\"submit\", function () {\r\n");
      out.write("\tif($(\"#idCheck\").text().indexOf(\"사용가능한 \")<= -1){\r\n");
      out.write("\t\talert(\"사용가능한 아이디를 입력해주세요\");\r\n");
      out.write("\t\t$(\"#id\").focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("});\r\n");
      out.write("  \r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("<!-- hearder -> h1 : 첫번째 나오는 제목 -->\r\n");
      out.write("\t<h2>회원가입</h2>\r\n");
      out.write("\t<form action=\"join.jsp\" method=\"post\" id=\"joinForm\">\r\n");
      out.write("    \r\n");
      out.write("<!--     아이디 입력 -->\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"id\">아이디 :</label>\r\n");
      out.write("<!--  아이디 입력 - 4자 이상 20자 이내 , 영문자와 숫자만 가능, 맨 앞자리는 영문자, 필수입력 -->\r\n");
      out.write("<!-- maxlength : 최대 입력 글자수, pattern : 입력 글자의 형식, \r\n");
      out.write("title : 마우스를 올려 놨을때 메시지, 또는 형식에 안맞을 때 사용하는 메세지  -->\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"id\" \r\n");
      out.write("      placeholder=\"아이디 입력\" name=\"id\"\r\n");
      out.write("      maxlength=\"20\" required=\"required\"\r\n");
      out.write("\t  pattern=\"^[A-Za-z][A-Za-z0-9]{3,19}$\" \r\n");
      out.write("\t  title=\"4-20자 영숫자, 맨 앞자는 영문자\" autocomplete=\"off\"\r\n");
      out.write("\t  />\r\n");
      out.write("    <div id=\"idCheck\">아이디를 입력하셔야만 합니다.</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("<!--     비밀번호 입력 -->\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"pw\">비밀번호:</label>\r\n");
      out.write("      <input type=\"password\" class=\"form-control\" id=\"pw\" \r\n");
      out.write("      \t\t maxlength=\"20\" required=\"required\"\r\n");
      out.write("\t\t\t pattern=\"^.{4,20}$\" title=\"4-20이내의 글자 입력\" \r\n");
      out.write("\t\t\t placeholder=\"비밀번호 입력\"\r\n");
      out.write("      \t\t name=\"pw\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("<!--     비밀번호 확인 입력 -->\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"pw2\">비밀번호 확인:</label>\r\n");
      out.write("      <input type=\"password\" class=\"form-control\" id=\"pw2\" \r\n");
      out.write("      \t\t maxlength=\"20\" required=\"required\"\r\n");
      out.write("\t\t\t pattern=\"^.{4,20}$\" title=\"4-20이내의 글자 입력\" \r\n");
      out.write("\t\t\t placeholder=\"비밀번호 확인입력\"\r\n");
      out.write("      \t\t name=\"pw2\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("<!--     이름입력 -->\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"name\">이름 :</label>\r\n");
      out.write("<!--  아이디 입력 - 2자 이상 10자 이내 , 한글만 가능, 필수입력 -->\r\n");
      out.write("<!-- maxlength : 최대 입력 글자수, pattern : 입력 글자의 형식, \r\n");
      out.write("title : 마우스를 올려 놨을때 메시지, 또는 형식에 안맞을 때 사용하는 메세지  -->\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"name\" \r\n");
      out.write("      placeholder=\"이름 입력\" name=\"name\"\r\n");
      out.write("      maxlength=\"10\" required=\"required\"\r\n");
      out.write("\t  pattern=\"^[가-힣]{2,10}$\" \r\n");
      out.write("\t  title=\"2-10자 한글\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("<!--     성별 입력 -->\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("        <label for=\"namd\">성별 :</label>\r\n");
      out.write("    \t<label class=\"radio-inline\">\r\n");
      out.write("    \t\t<input type=\"radio\" name=\"gender\" checked\r\n");
      out.write("    \t\t\tvalue = \"남자\" >남자\r\n");
      out.write("    \t</label>\r\n");
      out.write("    \t<label class=\"radio-inline\">\r\n");
      out.write("    \t\t<input type=\"radio\" name=\"gender\" \r\n");
      out.write("    \t\t\tvalue = \"여자\" >여자\r\n");
      out.write("    \t</label>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("<!--     생년월일 입력 -->\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"birth\">생년월일 :</label>\r\n");
      out.write("<!-- maxlength : 최대 입력 글자수, pattern : yyyy-mm-dd, \r\n");
      out.write("title : 마우스를 올려 놨을때 메시지, 또는 형식에 안맞을 때 사용하는 메세지  -->\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"birth\" \r\n");
      out.write("      placeholder=\"생년월일을  입력-클릭\" name=\"birth\"\r\n");
      out.write("      maxlength=\"10\" required=\"required\"\r\n");
      out.write("\t  pattern=\"^[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}$\" \r\n");
      out.write("\t  />\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<!--     전화번호 입력 -->\r\n");
      out.write("    <div class=\"form-group row\">\r\n");
      out.write("      <div class=\"col-xs-2\">\r\n");
      out.write("      <label for=\"tel\">핸드폰 :</label>\r\n");
      out.write("      </div>\r\n");
      out.write("       <div class=\"col-xs-2\">\r\n");
      out.write("\t      <select class=\"form-control\" id=\"tel1\" name=\"tel\">\r\n");
      out.write("\t    \t<option selected = \"selected\">010</option>\r\n");
      out.write("\t    \t<option>011</option>\r\n");
      out.write("\t    \t<option>016</option>\r\n");
      out.write("\t    \t<option>017</option>\r\n");
      out.write("\t    \t<option>018</option>\r\n");
      out.write("\t    \t<option>019</option>\r\n");
      out.write("\t      </select>\r\n");
      out.write("     </div>\r\n");
      out.write("      <div class=\"col-xs-2\">\r\n");
      out.write("<!-- maxlength : 최대 입력 글자수, pattern : yyyy-mm-dd, \r\n");
      out.write("title : 마우스를 올려 놨을때 메시지, 또는 형식에 안맞을 때 사용하는 메세지  -->\r\n");
      out.write("      <input type=\"number\" class=\"form-control\" id=\"tel2\" \r\n");
      out.write("      placeholder=\"3-4자리 숫자\" name=\"tel\"\r\n");
      out.write("      maxlength=\"4\" required=\"required\"\r\n");
      out.write("      pattern=\"^[0-9]{3,4}$\" title=\"숫자로 3-4자리입력\"\r\n");
      out.write("\t  />\r\n");
      out.write("\t  </div>\r\n");
      out.write("      <div class=\"col-xs-2\">\r\n");
      out.write("<!-- maxlength : 최대 입력 글자수, pattern : yyyy-mm-dd, \r\n");
      out.write("title : 마우스를 올려 놨을때 메시지, 또는 형식에 안맞을 때 사용하는 메세지  -->\r\n");
      out.write("      <input type=\"number\" class=\"form-control\" id=\"tel3\" \r\n");
      out.write("      placeholder=\"4자리 숫자\" name=\"tel\"\r\n");
      out.write("      maxlength=\"4\" required=\"required\"\r\n");
      out.write("      pattern=\"^[0-9]{4}$\" title=\"숫자로 4자리입력\"\r\n");
      out.write("\t  />\r\n");
      out.write("\t  </div>\r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write("<!--     이메일 입력 -->\r\n");
      out.write("\t  <div class=\"form-group\">\r\n");
      out.write("      <label for=\"id\">아이디 :</label>\r\n");
      out.write("<!--  아이디 입력 - 4자 이상 20자 이내 , 영문자와 숫자만 가능, 맨 앞자리는 영문자, 필수입력 -->\r\n");
      out.write("<!-- maxlength : 최대 입력 글자수, pattern : 입력 글자의 형식, \r\n");
      out.write("title : 마우스를 올려 놨을때 메시지, 또는 형식에 안맞을 때 사용하는 메세지 \r\n");
      out.write("type=\"email\" 작성하면 에 이메일 형식에 맞는지도 검사한다.   -->\r\n");
      out.write("\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"email\" \r\n");
      out.write("      placeholder=\"이메일입력\" name=\"email\"\r\n");
      out.write("      maxlength=\"50\" required=\"required\"\r\n");
      out.write("\t  title=\"이메일 형식 - 예 : ○○○○123@nate.com\"\r\n");
      out.write("\t  /><br/>\r\n");
      out.write("\t  이메일 형식 - 예 : ○○○○123@nate.com\r\n");
      out.write("    </div>   \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <button type=\"submit\" class=\"btn btn-default\">회원가입</button>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
