/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2020-01-02 07:12:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- bootstrap 라이브러리 등록 : CDN 방식 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#id\").on(\"keyup\", function(){\r\n");
      out.write("\t\tvar id = $(\"#id\").val().trim();\r\n");
      out.write("\t\t$(\"#id\").val(id);\r\n");
      out.write("\t\tif(id.length == 0){\r\n");
      out.write("\t\t\t$(\"#idCheck\").html(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t} else if(id.length < 4 || id.length > 20){\r\n");
      out.write("\t\t\t$(\"#idCheck\").html(\"아이디는 4자이상 20자이내로 작성해주세요.\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t// 적당한 아이디를 입력한 경우 ajax를 이용해 서-버에서 아이디 확인\r\n");
      out.write("\t\t\t$(\"#idCheck\").load(\"/ajax/idCheck.do?id=\" + id);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}); // 아이디 중복체크 끝\r\n");
      out.write("\t\r\n");
      out.write("\t// 데이터를 넘기기 전 데이터 확인 처리 이벤트\r\n");
      out.write("\t$(\"#joinForm\").on(\"submit\", function(){\r\n");
      out.write("\t\tif($(\"#idCheck\").text().indexOf(\"사용 가능한\") <= -1){\r\n");
      out.write("\t\t\talert(\"사용가능한 아이디를 입력해주세요!\");\r\n");
      out.write("\t\t\t$(\"#id\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"#pw\").val() != $(\"#pw2\").val()){\r\n");
      out.write("\t\t\talert(\"비밀번호 확인이 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t$(\"#pw\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#birth\").datepicker({\r\n");
      out.write("\t\t\tchangeMonth : true,\r\n");
      out.write("\t\t\tchangeYear : true\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#birth\").datepicker(\"option\", \"dateFormat\", \"yy-mm-dd\");\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<!-- header tag -> h1 : 첫번째 나오는 제목이 제일 크므로 1~6 순으로 크기가 큼 / 자동 줄 바꿈이 됨 -->\r\n");
      out.write("\t\t<h2>회원가입</h2>\r\n");
      out.write("\t\t<form action=\"join.do\" method=\"post\" id=\"joinForm\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<!-- \t\t\t아이디입력 -->\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<!-- id 4자~20자 -->\r\n");
      out.write("\t\t\t\t<!-- max length : 최대 입력 글자수, pattern : 입력 글자의 형식, title : 마우스를 올려두거나 또는 형식에 안맞을 때 뜨는 메세지-->\r\n");
      out.write("\t\t\t\t<label for=\"ID\">아이디 : </label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"id\" placeholder=\"Enter ID\" maxlength=\"20\"\r\n");
      out.write("\t\t\t\t\trequired=\"required\" pattern=\"^[A-Za-z][A-za-z0-9]{3,19}$\"\r\n");
      out.write("\t\t\t\t\ttitle=\"4-20영숫자, 맨 앞자는 영문자\" name=\"id\" autocomplete=\"off\"/>\r\n");
      out.write("\t\t\t\t\t<div id =\"idCheck\">아이디를 입력하세요.</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- \t\t\t비밀번호 입력 -->\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label for=\"pw\">비밀번호 : </label> <input type=\"password\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"pw\" placeholder=\"Enter password\"\r\n");
      out.write("\t\t\t\t\tmaxlength=\"20\" required=\"required\" pattern=\"^.{4,20}$\"\r\n");
      out.write("\t\t\t\t\ttitle=\"4-20이내의 글자 입력\" name=\"pw\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- \t\t\t비밀번호 확인 입력 -->\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label for=\"pw2\">비밀번호확인 : </label> <input type=\"password\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"pw2\" placeholder=\"비밀번호 확인\" maxlength=\"20\"\r\n");
      out.write("\t\t\t\t\trequired=\"required\" pattern=\"^.{4,20}$\" title=\"4-20이내의 글자 입력\"\r\n");
      out.write("\t\t\t\t\tname=\"pw2\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"checkPwResult\"></div>\r\n");
      out.write("\t\t\t<!-- \t\t\t이름 입력 -->\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<!-- 이름 2자~10자, 한글만 가능, 필수입력 -->\r\n");
      out.write("\t\t\t\t<label for=\"name\">닉네임 : </label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"nickName\" placeholder=\"닉네임을 입력하세요.\"\r\n");
      out.write("\t\t\t\t\tmaxlength=\"10\" required=\"required\" pattern=\"^.{2,10}$\"\r\n");
      out.write("\t\t\t\t\ttitle=\"2-10 한글\" name=\"nickName\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<!-- 이름 2자~10자, 한글만 가능, 필수입력 -->\r\n");
      out.write("\t\t\t\t<label for=\"addr\">주소 : </label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"addr\" placeholder=\"주소을 입력하세요.\"\r\n");
      out.write("\t\t\t\t\tmaxlength=\"20\" required=\"required\" pattern=\"^.{2,20}$\"\r\n");
      out.write("\t\t\t\t\tname=\"addr\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- \t\t\t이메일 입력란 -->\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<!-- id 4자~20자 -->\r\n");
      out.write("\t\t\t\t<!-- max length : 최대 입력 글자수, pattern : 입력 글자의 형식, title : 마우스를 올려두거나 또는 형식에 안맞을 때 뜨는 메세지-->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\ttype을 email로 쓰면 이메일 형식에 맞는지도 검사한다. -->\r\n");
      out.write("\t\t\t\t<label for=\"email\">email : </label> <input type=\"email\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"email\" placeholder=\"Enter email\"\r\n");
      out.write("\t\t\t\t\tmaxlength=\"100\" required=\"required\"\r\n");
      out.write("\t\t\t\t\tpattern=\"^[a-zA-Z0-9._%+_]*@[a-zA-Z0-9.-]+.[a-zA-Z]{2,6}$\"\r\n");
      out.write("\t\t\t\t\ttitle=\"example) exam@exam.com\" name=\"email\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<!-- id 4자~20자 -->\r\n");
      out.write("\t\t\t\t<!-- max length : 최대 입력 글자수, pattern : 입력 글자의 형식, title : 마우스를 올려두거나 또는 형식에 안맞을 때 뜨는 메세지-->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\ttype을 email로 쓰면 이메일 형식에 맞는지도 검사한다. -->\r\n");
      out.write("\t\t\t\t<label for=\"question\">비밀번호 찾기 질문 : </label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"question\" placeholder=\"예) 졸업한 초등학교의 이름은?\"\r\n");
      out.write("\t\t\t\t\tmaxlength=\"100\" required=\"required\"\r\n");
      out.write("\t\t\t\t\ttitle=\"비밀번호 찾기 질문\" name=\"question\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label for=\"answer\">비밀번호 찾기 답변 : </label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tclass=\"form-control\" id=\"answer\" placeholder=\"예) 어때초등학교\"\r\n");
      out.write("\t\t\t\t\tmaxlength=\"100\" required=\"required\"\r\n");
      out.write("\t\t\t\t\ttitle=\"비밀번호 찾기 답변\" name=\"answer\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- \t\t\t전화번호 입력란 -->\r\n");
      out.write("\t\t\t<div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t<div class=col-md-2>\r\n");
      out.write("\t\t\t\t\t<label for=\"tel\">전화번호 : </label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t<select class=\"form-control\" id=\"tel\" name=\"tel\">\r\n");
      out.write("\t\t\t\t\t\t<option>010</option>\r\n");
      out.write("\t\t\t\t\t\t<option>011</option>\r\n");
      out.write("\t\t\t\t\t\t<option>016</option>\r\n");
      out.write("\t\t\t\t\t\t<option>017</option>\r\n");
      out.write("\t\t\t\t\t\t<option>018</option>\r\n");
      out.write("\t\t\t\t\t\t<option>019</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t<input type=\"number\" class=\"form-control\" id=\"tel2\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"3~4자리\" maxlength=\"4\" pattern=\"\\d{3,4}$\"\r\n");
      out.write("\t\t\t\t\t\t name=\"tel\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t<input type=\"number\" class=\"form-control\" id=\"tel3\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"4자리\" maxlength=\"4\" pattern=\"\\d{4}$\"\r\n");
      out.write("\t\t\t\t\t \tname=\"tel\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label for=\"multiFile\">이미지 첨부</label> \r\n");
      out.write("\t\t\t\t<input type=\"file\" name=\"photo\" class=\"form-control\" id=\"photo\"><br/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 버튼의 기본 타입은 submit -->\r\n");
      out.write("\t\t\t<button class=\"btn btn-default\">Join</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tconst pw = document.querySelector(\"#pw\");\r\n");
      out.write("\t\tconst pw2 = document.querySelector(\"#pw2\");\r\n");
      out.write("\t\tconst checkPwResult = document.querySelector(\"#checkPwResult\");\r\n");
      out.write("\t\tfunction checkPw(){\r\n");
      out.write("\t\t\tif(pw.value === pw2.value){\r\n");
      out.write("\t\t\t\tcheckPwResult.innerHTML = \"<span style='color: blue;'>비밀번호가 일치합니다.</span>\";\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tcheckPwResult.innerHTML = \"<span style='color: red;'>비밀번호가 일치하지 않습니다.</span>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tpw2.addEventListener(\"keyup\", checkPw);\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
